apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.diophanatic_question_database.name }}
  labels:
    app: {{ .Values.diophanatic_question_database.name }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.diophanatic_question_database.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.diophanatic_question_database.name }}
    spec:
#      securityContext: Comment out on GCP
#        fsGroup: 1000
#        runAsUser: 1000
      containers:
      - image: "{{ .Values.diophanatic_question_database.repository }}:{{ .Values.diophanatic_webapp_image.version }}"
        imagePullPolicy: {{ .Values.diophanatic_webapp_image.pullPolicy }}
        name: {{ .Values.diophanatic_question_database.name }}
        ports:
        - containerPort: {{ .Values.diophanatic_question_database.port }}
          protocol: TCP
          name: http
{{/*        livenessProbe:*/}}
{{/*          httpGet:*/}}
{{/*            path: /*/}}
{{/*            port: http*/}}
{{/*          initialDelaySeconds: {{ .Values.diophanatic_webapp_image.initialDelaySeconds }}*/}}
{{/*        readinessProbe:*/}}
{{/*          httpGet:*/}}
{{/*            path: /*/}}
{{/*            port: http*/}}
{{/*          initialDelaySeconds: {{ .Values.diophanatic_webapp_image.initialDelaySeconds }}*/}}
