apiVersion: v1
kind: Service
metadata:
  name: diophanatic-webapp-service
spec:
  selector:
    app: k8s-test-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.diophanatic_webapp_image.port }}
      name: http
  type: LoadBalancer
