# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Webapp, push docker image

on:
  push:
    branches:
      - '**'

jobs:
  test:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest]
          python-version: ["3.10"]
          experimental: [false]  # These versions must pass.
      steps:
      - uses: actions/checkout@v2  # Checkout repo.

      - name: Set up production Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display python version.
        run: python --version --version && which python

      - name: Install dependencies
        working-directory: webapp
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements_dev.txt
      - name: Test with pytest --cov=./ --mypy -vv
        working-directory: webapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pytest --cov=./ --mypy -vv
          coverage xml -i
          coveralls --service=github

  coveralls_finish:
      needs: test
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished report
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          parallel-finished: true
          flag-name: github_action_tests
          base-path: '.webapp/'
          debug: true

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.5
        with:
          addLatest: true
          directory: ./webapp
          dockerfile: ./webapp/Dockerfile
          image: toonarmycaptain/diophanatic-webapp
          registry: docker.io
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
